import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'
import Header from '@/widgets/Header/page'
import Footer from '@/widgets/Footer/page'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Header/>
                <main>
                    {children}
                </main>
                <Footer/>
            </body>
        </html>
    )
}
